import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Static checks on 0020_member_profile_extended.sql — same convention as
// every prior migration test in this project (no live Postgres available
// to run the actual trigger against; see phase2_rls.test.js's own
// documented limitation). What this DOES catch: a column silently
// dropped/renamed, the sequence/trigger shape drifting from "fires once
// per row, before insert" into something that wouldn't survive a bulk
// insert, or a stray members_* policy sneaking permission changes into
// what's supposed to be a purely additive migration.

const migrationsDir = dirname(fileURLToPath(import.meta.url));

function allMigrationSql() {
  return readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((f) => readFileSync(join(migrationsDir, f), "utf8"))
    .join("\n\n");
}

function thisMigrationSql() {
  return readFileSync(join(migrationsDir, "0020_member_profile_extended.sql"), "utf8");
}

describe("0020_member_profile_extended.sql (static)", () => {
  let sql, ownSql;
  beforeAll(() => {
    sql = allMigrationSql();
    ownSql = thisMigrationSql();
  });

  it("adds all 7 new columns via ADD COLUMN", () => {
    expect(ownSql).toMatch(/alter table members add column member_id text unique/);
    expect(ownSql).toMatch(/alter table members add column nationality text default 'Ghana'/);
    expect(ownSql).toMatch(/alter table members add column marital_status text/);
    expect(ownSql).toMatch(/alter table members add column whatsapp_number text/);
    expect(ownSql).toMatch(/alter table members add column educational_professional_background text/);
    expect(ownSql).toMatch(/alter table members add column educational_institution text/);
    expect(ownSql).toMatch(/alter table members add column workplace_name text/);
  });

  it("marital_status is constrained to the 6 spec'd values", () => {
    for (const value of ["Single", "Married", "Divorced", "Widowed", "Engaged", "Separated"]) {
      expect(ownSql).toContain(`'${value}'`);
    }
  });

  it("never renames or drops an existing members column, anywhere in migration history", () => {
    expect(sql).not.toMatch(/alter table members\s+rename column/i);
    expect(sql).not.toMatch(/alter table members\s+drop column/i);
  });

  it("member_id is generated by a BEFORE INSERT ... FOR EACH ROW trigger (fires per-row, covers bulk insert too)", () => {
    expect(ownSql).toMatch(/create sequence member_id_seq/);
    expect(ownSql).toMatch(/create trigger on_member_insert_set_id\s+before insert on members\s+for each row/);
    expect(ownSql).toMatch(/nextval\('member_id_seq'\)/);
  });

  it("the id format is 'PIWC-' + year + 4-digit zero-padded global sequence, not reset per year", () => {
    expect(ownSql).toMatch(/'PIWC-'/);
    expect(ownSql).toMatch(/lpad\(nextval\('member_id_seq'\)::text, 4, '0'\)/);
    // The sequence itself carries no year-scoping (no per-year reset/restart) —
    // it's declared once, globally, and only ever read via nextval().
    expect(ownSql).not.toMatch(/alter sequence member_id_seq restart/i);
  });

  it("member_id is immutable once set (a BEFORE UPDATE trigger guards it)", () => {
    expect(ownSql).toMatch(/create trigger on_member_update_protect_id\s+before update on members\s+for each row/);
    expect(ownSql).toMatch(/old\.member_id is not null and new\.member_id is distinct from old\.member_id/);
  });

  it("backfills existing (pre-migration) rows rather than leaving them permanently NULL", () => {
    expect(ownSql).toMatch(/where member_id is null/);
  });

  it("touches no RLS policy — purely additive, the existing role matrix is untouched", () => {
    expect(ownSql).not.toMatch(/create policy members_/);
    expect(ownSql).not.toMatch(/alter policy/i);
  });
});
